### ISSUE TITLE
Get process state does not work while polling

### ISSUE THREAD

**Issue by aboroska** [andytill/erlyberly#23]
When one clicks on ```Get process state``` while processes being polled the function does not work.

The workaround is to turn off process polling before asking the state.

**Comment by andytill** [comment]
This is happening because the menu is only enabled when a process is selected, and the processes blasts the previous table and loses the selection making the menu go disabled.

We could make the process that was clicked stay the process that will be operated on by the menu even if the process underneath the mouse changes.

**Comment by andytill** [comment]
Fixed. Process polling is suspended while the right click context menu is shown.
